language: objective-c
osx_image: xcode7.3

notifications:
  slack: swiftgg:GTctPDWV5h8pPzaagds051WS
  email: false

before_install:
  - gem install cocoapods --pre
  - brew update
  - brew install carthage

before_script:
  - carthage bootstrap --verbose --platform ios --color auto --no-use-binaries

script:
  - xctool -workspace GGQ.xcworkspace -scheme GGQ-Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
